openapi: 3.0.1
info:
  description: Upload and manage files.
  title: Files
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-api-use-case: "When launching a company rebrand, upload a new set of branded\
    \ images and assets to the file manager so that marketing and sales teams can\
    \ update their assets accordingly."
  x-hubspot-related-documentation:
  - name: Files Guide
    url: https://developers.hubspot.com/docs/guides/api/library/files
  x-hubspot-introduction: "Use the files API to manage and store files in HubSpot's\
    \ file manager tool. Files can be used throughout other HubSpot tools, such as\
    \ inserting image files into emails."
servers:
- url: https://api.hubapi.com
tags:
- name: Files
- name: Folders
paths:
  /files/v3/files/{fileId}/gdpr-delete:
    delete:
      description: Delete a file in accordance with GDPR regulations.
      operationId: "delete-/files/v3/files/{fileId}/gdpr-delete_delete"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: GDPR-delete file
      tags:
      - Files
  /files/v3/files/{fileId}:
    delete:
      description: Delete a file by ID
      operationId: "delete-/files/v3/files/{fileId}_archive"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Delete file by ID
      tags:
      - Files
    get:
      description: Retrieve a file by its ID.
      operationId: "get-/files/v3/files/{fileId}_getById"
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Retrieve file by ID
      tags:
      - Files
    patch:
      description: Update properties of file by ID.
      operationId: "patch-/files/v3/files/{fileId}_updateProperties"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Update file properties
      tags:
      - Files
    put:
      description: Replace existing file data with new file data. Can be used to change
        image content without having to upload a new file and update all references.
      operationId: "put-/files/v3/files/{fileId}_replace"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Replace file
      tags:
      - Files
  /files/v3/folders/{folderId}:
    delete:
      description: Delete folder by ID.
      operationId: "delete-/files/v3/folders/{folderId}_archive"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Delete folder by ID
      tags:
      - Folders
    get:
      description: Retrieve a folder by its ID.
      operationId: "get-/files/v3/folders/{folderId}_getById"
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Retrieve folder by ID
      tags:
      - Folders
    patch:
      description: "Update a folder's properties, identified by folder ID."
      operationId: "patch-/files/v3/folders/{folderId}_updateProperties"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Update folder properties by folder ID
      tags:
      - Folders
  /files/v3/files:
    post:
      description: Upload a single file with content specified in request body.
      operationId: post-/files/v3/files_upload
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Upload file
      tags:
      - Files
  /files/v3/folders:
    post:
      description: Creates a folder.
      operationId: post-/files/v3/folders_create
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Create folder
      tags:
      - Folders
  /files/v3/files/{fileId}/signed-url:
    get:
      description: Generates signed URL that allows temporary access to a private
        file.
      operationId: "get-/files/v3/files/{fileId}/signed-url_getSignedUrl"
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Get signed URL to access private file
      tags:
      - Files
  /files/v3/files/import-from-url/async:
    post:
      description: Asynchronously imports the file at the given URL into the file
        manager.
      operationId: post-/files/v3/files/import-from-url/async_importFromUrl
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Import file from URL
      tags:
      - Files
  /files/v3/files/stat/{path}:
    get:
      description: Retrieve a file by its path.
      operationId: "get-/files/v3/files/stat/{path}_getMetadata"
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Retrieve file by path
      tags:
      - Files
  /files/v3/folders/search:
    get:
      description: Search for folders. Does not contain hidden or archived folders.
      operationId: get-/files/v3/folders/search_doSearch
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Search folders
      tags:
      - Folders
  /files/v3/folders/update/async/tasks/{taskId}/status:
    get:
      description: Check status of folder update. Folder updates happen asynchronously.
      operationId: "get-/files/v3/folders/update/async/tasks/{taskId}/status_checkUpdateStatus"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Check folder update status
      tags:
      - Folders
  /files/v3/files/search:
    get:
      description: Search through files in the file manager. Does not display hidden
        or archived files.
      operationId: get-/files/v3/files/search_doSearch
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Search files
      tags:
      - Files
  /files/v3/folders/{folderPath}:
    delete:
      description: "Delete a folder, identified by its path."
      operationId: "delete-/files/v3/folders/{folderPath}_archiveByPath"
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Delete folder by path
      tags:
      - Folders
    get:
      description: "Retrieve a folder, identified by its path."
      operationId: "get-/files/v3/folders/{folderPath}_getByPath"
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Retrieve folder by path
      tags:
      - Folders
  /files/v3/folders/update/async:
    post:
      description: Update properties of folder by given ID. This action happens asynchronously
        and will update all of the folder's children as well.
      operationId: post-/files/v3/folders/update/async_updatePropertiesRecursively
      security:
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Update folder properties
      tags:
      - Folders
  /files/v3/files/import-from-url/async/tasks/{taskId}/status:
    get:
      description: Check the status of requested import.
      operationId: "get-/files/v3/files/import-from-url/async/tasks/{taskId}/status_checkImport"
      security:
      - private_apps:
        - files.ui_hidden.read
      - oauth2:
        - files.ui_hidden.read
      - oauth2:
        - files
      - private_apps:
        - files
      summary: Check import status
      tags:
      - Files
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            files: Read from and write to my Files
            files.ui_hidden.read: View hidden files
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
