openapi: 3.0.1
info:
  title: CRM Associations
  version: v4
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: STARTER
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "When an existing contact has moved to a new company, update\
    \ their associated company to keep your CRM up to date."
  x-hubspot-related-documentation:
  - name: Associations guide
    url: https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4
  x-hubspot-introduction: "Use the associations API to create, retrieve, update, or\
    \ delete associations between records, or between records and activities. "
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Report
- name: Basic
paths:
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive:
    post:
      description: Batch delete associations for objects
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/archive_archive"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Delete
      tags:
      - Batch
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create:
    post:
      description: Batch create associations for objects
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/create_create"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Create
      tags:
      - Batch
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/usage/high-usage-report/{userId}:
    post:
      description: Requests a report of all objects in the portal which have a high
        usage of associations
      operationId: "post-/crm/v4/associations/usage/high-usage-report/{userId}_request"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Report
      tags:
      - Report
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive:
    post:
      description: Batch delete specific association labels for objects. Deleting
        an unlabeled association will also delete all labeled associations between
        those two objects
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/labels/archive_archiveLabels"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Delete Specific Labels
      tags:
      - Batch
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read:
    post:
      description: "Batch read associations for objects to specific object type. The\
        \ 'after' field in a returned paging object  can be added alongside the 'id'\
        \ to retrieve the next page of associations from that objectId. The 'link'\
        \ field is deprecated and should be ignored. Note: The 'paging' field will\
        \ only be present if there are more pages and absent otherwise."
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/read_getPage"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Read
      tags:
      - Batch
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default:
    post:
      description: Create the default (most generic) association type between two
        object types
      operationId: "post-/crm/v4/associations/{fromObjectType}/{toObjectType}/batch/associate/default_createDefault"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: ' Create Default Associations'
      tags:
      - Batch
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}:
    delete:
      description: deletes all associations between two records.
      operationId: "delete-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_archive"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Delete
      tags:
      - Basic
    put:
      description: Set association labels between two records.
      operationId: "put-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}/{toObjectId}_create"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Create
      tags:
      - Basic
  /crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}:
    get:
      description: List all associations of an object by object type. Limit 500 per
        call.
      operationId: "get-/crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType}_getPage"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: List
      tags:
      - Basic
  /crm/v4/objects/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}:
    put:
      description: Create the default (most generic) association type between two
        object types
      operationId: "put-/crm/v4/objects/{fromObjectType}/{fromObjectId}/associations/default/{toObjectType}/{toObjectId}_createDefault"
      security:
      - private_apps:
        - crm.objects.listings.write
      - private_apps:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.appointments.write
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - private_apps:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.appointments.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.courses.write
      - private_apps:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.courses.read
      - private_apps:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
      summary: Create Default
      tags:
      - Basic
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.custom.read: View custom object records
            tickets: Read and write tickets
            crm.objects.goals.read: Read goals
            media_bridge.read: Read media and media events
            crm.objects.custom.write: Change custom object records
            e-commerce: e-commerce
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.courses.write: Write courses
            crm.objects.carts.write: Write cart
            crm.objects.listings.read: Read listings
            crm.objects.contacts.read: ' '
            crm.objects.orders.read: Read Orders
            crm.objects.services.read: Read services
            crm.objects.quotes.read: Quotes
            crm.objects.orders.write: Write orders
            crm.objects.carts.read: Read carts
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.leads.write: Modify lead objects
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.users.write: Write User CRM objects
            crm.objects.contacts.write: ' '
            crm.objects.companies.write: ' '
            crm.objects.listings.write: Write listings
            crm.objects.line_items.write: Line Items
            crm.objects.deals.write: ' '
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.invoices.read: Read invoices objects
            crm.objects.deals.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.line_items.read: Line Items
            crm.objects.services.write: Write services
            crm.objects.appointments.write: Write appointments
            crm.objects.leads.read: Read lead objects
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.appointments.read: Read appointments
            crm.objects.companies.read: ' '
            crm.objects.users.read: Read User CRM objects
            crm.objects.quotes.write: Quotes
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: STARTER
x-hubspot-documentation-banner: NONE
