/*
Properties

All HubSpot objects store data in default and custom properties. These endpoints provide access to read and modify object properties in HubSpot.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CollectionResponsePropertyNoPaging type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionResponsePropertyNoPaging{}

// CollectionResponsePropertyNoPaging struct for CollectionResponsePropertyNoPaging
type CollectionResponsePropertyNoPaging struct {
	Results []Property `json:"results"`
}

// NewCollectionResponsePropertyNoPaging instantiates a new CollectionResponsePropertyNoPaging object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionResponsePropertyNoPaging(results []Property) *CollectionResponsePropertyNoPaging {
	this := CollectionResponsePropertyNoPaging{}
	this.Results = results
	return &this
}

// NewCollectionResponsePropertyNoPagingWithDefaults instantiates a new CollectionResponsePropertyNoPaging object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionResponsePropertyNoPagingWithDefaults() *CollectionResponsePropertyNoPaging {
	this := CollectionResponsePropertyNoPaging{}
	return &this
}

// GetResults returns the Results field value
func (o *CollectionResponsePropertyNoPaging) GetResults() []Property {
	if o == nil {
		var ret []Property
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *CollectionResponsePropertyNoPaging) GetResultsOk() ([]Property, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *CollectionResponsePropertyNoPaging) SetResults(v []Property) {
	o.Results = v
}

func (o CollectionResponsePropertyNoPaging) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionResponsePropertyNoPaging) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullableCollectionResponsePropertyNoPaging struct {
	value *CollectionResponsePropertyNoPaging
	isSet bool
}

func (v NullableCollectionResponsePropertyNoPaging) Get() *CollectionResponsePropertyNoPaging {
	return v.value
}

func (v *NullableCollectionResponsePropertyNoPaging) Set(val *CollectionResponsePropertyNoPaging) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionResponsePropertyNoPaging) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionResponsePropertyNoPaging) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionResponsePropertyNoPaging(val *CollectionResponsePropertyNoPaging) *NullableCollectionResponsePropertyNoPaging {
	return &NullableCollectionResponsePropertyNoPaging{value: val, isSet: true}
}

func (v NullableCollectionResponsePropertyNoPaging) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionResponsePropertyNoPaging) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


