/*
Notes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SimplePublicObjectInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimplePublicObjectInput{}

// SimplePublicObjectInput struct for SimplePublicObjectInput
type SimplePublicObjectInput struct {
	ObjectWriteTraceId *string `json:"objectWriteTraceId,omitempty"`
	Properties map[string]string `json:"properties"`
}

type _SimplePublicObjectInput SimplePublicObjectInput

// NewSimplePublicObjectInput instantiates a new SimplePublicObjectInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimplePublicObjectInput(properties map[string]string) *SimplePublicObjectInput {
	this := SimplePublicObjectInput{}
	this.Properties = properties
	return &this
}

// NewSimplePublicObjectInputWithDefaults instantiates a new SimplePublicObjectInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimplePublicObjectInputWithDefaults() *SimplePublicObjectInput {
	this := SimplePublicObjectInput{}
	return &this
}

// GetObjectWriteTraceId returns the ObjectWriteTraceId field value if set, zero value otherwise.
func (o *SimplePublicObjectInput) GetObjectWriteTraceId() string {
	if o == nil || IsNil(o.ObjectWriteTraceId) {
		var ret string
		return ret
	}
	return *o.ObjectWriteTraceId
}

// GetObjectWriteTraceIdOk returns a tuple with the ObjectWriteTraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplePublicObjectInput) GetObjectWriteTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectWriteTraceId) {
		return nil, false
	}
	return o.ObjectWriteTraceId, true
}

// HasObjectWriteTraceId returns a boolean if a field has been set.
func (o *SimplePublicObjectInput) HasObjectWriteTraceId() bool {
	if o != nil && !IsNil(o.ObjectWriteTraceId) {
		return true
	}

	return false
}

// SetObjectWriteTraceId gets a reference to the given string and assigns it to the ObjectWriteTraceId field.
func (o *SimplePublicObjectInput) SetObjectWriteTraceId(v string) {
	o.ObjectWriteTraceId = &v
}

// GetProperties returns the Properties field value
func (o *SimplePublicObjectInput) GetProperties() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *SimplePublicObjectInput) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *SimplePublicObjectInput) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o SimplePublicObjectInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimplePublicObjectInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectWriteTraceId) {
		toSerialize["objectWriteTraceId"] = o.ObjectWriteTraceId
	}
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *SimplePublicObjectInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSimplePublicObjectInput := _SimplePublicObjectInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSimplePublicObjectInput)

	if err != nil {
		return err
	}

	*o = SimplePublicObjectInput(varSimplePublicObjectInput)

	return err
}

type NullableSimplePublicObjectInput struct {
	value *SimplePublicObjectInput
	isSet bool
}

func (v NullableSimplePublicObjectInput) Get() *SimplePublicObjectInput {
	return v.value
}

func (v *NullableSimplePublicObjectInput) Set(val *SimplePublicObjectInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSimplePublicObjectInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSimplePublicObjectInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimplePublicObjectInput(val *SimplePublicObjectInput) *NullableSimplePublicObjectInput {
	return &NullableSimplePublicObjectInput{value: val, isSet: true}
}

func (v NullableSimplePublicObjectInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimplePublicObjectInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


