/*
Notes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SimplePublicObjectBatchInputUpsert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimplePublicObjectBatchInputUpsert{}

// SimplePublicObjectBatchInputUpsert struct for SimplePublicObjectBatchInputUpsert
type SimplePublicObjectBatchInputUpsert struct {
	IdProperty *string `json:"idProperty,omitempty"`
	ObjectWriteTraceId *string `json:"objectWriteTraceId,omitempty"`
	Id string `json:"id"`
	Properties map[string]string `json:"properties"`
}

type _SimplePublicObjectBatchInputUpsert SimplePublicObjectBatchInputUpsert

// NewSimplePublicObjectBatchInputUpsert instantiates a new SimplePublicObjectBatchInputUpsert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimplePublicObjectBatchInputUpsert(id string, properties map[string]string) *SimplePublicObjectBatchInputUpsert {
	this := SimplePublicObjectBatchInputUpsert{}
	this.Id = id
	this.Properties = properties
	return &this
}

// NewSimplePublicObjectBatchInputUpsertWithDefaults instantiates a new SimplePublicObjectBatchInputUpsert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimplePublicObjectBatchInputUpsertWithDefaults() *SimplePublicObjectBatchInputUpsert {
	this := SimplePublicObjectBatchInputUpsert{}
	return &this
}

// GetIdProperty returns the IdProperty field value if set, zero value otherwise.
func (o *SimplePublicObjectBatchInputUpsert) GetIdProperty() string {
	if o == nil || IsNil(o.IdProperty) {
		var ret string
		return ret
	}
	return *o.IdProperty
}

// GetIdPropertyOk returns a tuple with the IdProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplePublicObjectBatchInputUpsert) GetIdPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.IdProperty) {
		return nil, false
	}
	return o.IdProperty, true
}

// HasIdProperty returns a boolean if a field has been set.
func (o *SimplePublicObjectBatchInputUpsert) HasIdProperty() bool {
	if o != nil && !IsNil(o.IdProperty) {
		return true
	}

	return false
}

// SetIdProperty gets a reference to the given string and assigns it to the IdProperty field.
func (o *SimplePublicObjectBatchInputUpsert) SetIdProperty(v string) {
	o.IdProperty = &v
}

// GetObjectWriteTraceId returns the ObjectWriteTraceId field value if set, zero value otherwise.
func (o *SimplePublicObjectBatchInputUpsert) GetObjectWriteTraceId() string {
	if o == nil || IsNil(o.ObjectWriteTraceId) {
		var ret string
		return ret
	}
	return *o.ObjectWriteTraceId
}

// GetObjectWriteTraceIdOk returns a tuple with the ObjectWriteTraceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimplePublicObjectBatchInputUpsert) GetObjectWriteTraceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectWriteTraceId) {
		return nil, false
	}
	return o.ObjectWriteTraceId, true
}

// HasObjectWriteTraceId returns a boolean if a field has been set.
func (o *SimplePublicObjectBatchInputUpsert) HasObjectWriteTraceId() bool {
	if o != nil && !IsNil(o.ObjectWriteTraceId) {
		return true
	}

	return false
}

// SetObjectWriteTraceId gets a reference to the given string and assigns it to the ObjectWriteTraceId field.
func (o *SimplePublicObjectBatchInputUpsert) SetObjectWriteTraceId(v string) {
	o.ObjectWriteTraceId = &v
}

// GetId returns the Id field value
func (o *SimplePublicObjectBatchInputUpsert) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SimplePublicObjectBatchInputUpsert) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SimplePublicObjectBatchInputUpsert) SetId(v string) {
	o.Id = v
}

// GetProperties returns the Properties field value
func (o *SimplePublicObjectBatchInputUpsert) GetProperties() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *SimplePublicObjectBatchInputUpsert) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *SimplePublicObjectBatchInputUpsert) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o SimplePublicObjectBatchInputUpsert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimplePublicObjectBatchInputUpsert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdProperty) {
		toSerialize["idProperty"] = o.IdProperty
	}
	if !IsNil(o.ObjectWriteTraceId) {
		toSerialize["objectWriteTraceId"] = o.ObjectWriteTraceId
	}
	toSerialize["id"] = o.Id
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *SimplePublicObjectBatchInputUpsert) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSimplePublicObjectBatchInputUpsert := _SimplePublicObjectBatchInputUpsert{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSimplePublicObjectBatchInputUpsert)

	if err != nil {
		return err
	}

	*o = SimplePublicObjectBatchInputUpsert(varSimplePublicObjectBatchInputUpsert)

	return err
}

type NullableSimplePublicObjectBatchInputUpsert struct {
	value *SimplePublicObjectBatchInputUpsert
	isSet bool
}

func (v NullableSimplePublicObjectBatchInputUpsert) Get() *SimplePublicObjectBatchInputUpsert {
	return v.value
}

func (v *NullableSimplePublicObjectBatchInputUpsert) Set(val *SimplePublicObjectBatchInputUpsert) {
	v.value = val
	v.isSet = true
}

func (v NullableSimplePublicObjectBatchInputUpsert) IsSet() bool {
	return v.isSet
}

func (v *NullableSimplePublicObjectBatchInputUpsert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimplePublicObjectBatchInputUpsert(val *SimplePublicObjectBatchInputUpsert) *NullableSimplePublicObjectBatchInputUpsert {
	return &NullableSimplePublicObjectBatchInputUpsert{value: val, isSet: true}
}

func (v NullableSimplePublicObjectBatchInputUpsert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimplePublicObjectBatchInputUpsert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


