/*
Files

Upload and manage files.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CollectionResponseFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionResponseFile{}

// CollectionResponseFile Collections of files
type CollectionResponseFile struct {
	Paging *Paging `json:"paging,omitempty"`
	// 
	Results []File `json:"results"`
}

type _CollectionResponseFile CollectionResponseFile

// NewCollectionResponseFile instantiates a new CollectionResponseFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionResponseFile(results []File) *CollectionResponseFile {
	this := CollectionResponseFile{}
	this.Results = results
	return &this
}

// NewCollectionResponseFileWithDefaults instantiates a new CollectionResponseFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionResponseFileWithDefaults() *CollectionResponseFile {
	this := CollectionResponseFile{}
	return &this
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *CollectionResponseFile) GetPaging() Paging {
	if o == nil || IsNil(o.Paging) {
		var ret Paging
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionResponseFile) GetPagingOk() (*Paging, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *CollectionResponseFile) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given Paging and assigns it to the Paging field.
func (o *CollectionResponseFile) SetPaging(v Paging) {
	o.Paging = &v
}

// GetResults returns the Results field value
func (o *CollectionResponseFile) GetResults() []File {
	if o == nil {
		var ret []File
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *CollectionResponseFile) GetResultsOk() ([]File, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *CollectionResponseFile) SetResults(v []File) {
	o.Results = v
}

func (o CollectionResponseFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionResponseFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *CollectionResponseFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCollectionResponseFile := _CollectionResponseFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCollectionResponseFile)

	if err != nil {
		return err
	}

	*o = CollectionResponseFile(varCollectionResponseFile)

	return err
}

type NullableCollectionResponseFile struct {
	value *CollectionResponseFile
	isSet bool
}

func (v NullableCollectionResponseFile) Get() *CollectionResponseFile {
	return v.value
}

func (v *NullableCollectionResponseFile) Set(val *CollectionResponseFile) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionResponseFile) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionResponseFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionResponseFile(val *CollectionResponseFile) *NullableCollectionResponseFile {
	return &NullableCollectionResponseFile{value: val, isSet: true}
}

func (v NullableCollectionResponseFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionResponseFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


