/*
Files

Upload and manage files.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FolderUpdateInputWithId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderUpdateInputWithId{}

// FolderUpdateInputWithId struct for FolderUpdateInputWithId
type FolderUpdateInputWithId struct {
	ParentFolderId *int64 `json:"parentFolderId,omitempty"`
	Name *string `json:"name,omitempty"`
	Id string `json:"id"`
}

type _FolderUpdateInputWithId FolderUpdateInputWithId

// NewFolderUpdateInputWithId instantiates a new FolderUpdateInputWithId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderUpdateInputWithId(id string) *FolderUpdateInputWithId {
	this := FolderUpdateInputWithId{}
	this.Id = id
	return &this
}

// NewFolderUpdateInputWithIdWithDefaults instantiates a new FolderUpdateInputWithId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderUpdateInputWithIdWithDefaults() *FolderUpdateInputWithId {
	this := FolderUpdateInputWithId{}
	return &this
}

// GetParentFolderId returns the ParentFolderId field value if set, zero value otherwise.
func (o *FolderUpdateInputWithId) GetParentFolderId() int64 {
	if o == nil || IsNil(o.ParentFolderId) {
		var ret int64
		return ret
	}
	return *o.ParentFolderId
}

// GetParentFolderIdOk returns a tuple with the ParentFolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderUpdateInputWithId) GetParentFolderIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ParentFolderId) {
		return nil, false
	}
	return o.ParentFolderId, true
}

// HasParentFolderId returns a boolean if a field has been set.
func (o *FolderUpdateInputWithId) HasParentFolderId() bool {
	if o != nil && !IsNil(o.ParentFolderId) {
		return true
	}

	return false
}

// SetParentFolderId gets a reference to the given int64 and assigns it to the ParentFolderId field.
func (o *FolderUpdateInputWithId) SetParentFolderId(v int64) {
	o.ParentFolderId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FolderUpdateInputWithId) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderUpdateInputWithId) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FolderUpdateInputWithId) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FolderUpdateInputWithId) SetName(v string) {
	o.Name = &v
}

// GetId returns the Id field value
func (o *FolderUpdateInputWithId) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FolderUpdateInputWithId) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FolderUpdateInputWithId) SetId(v string) {
	o.Id = v
}

func (o FolderUpdateInputWithId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderUpdateInputWithId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParentFolderId) {
		toSerialize["parentFolderId"] = o.ParentFolderId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *FolderUpdateInputWithId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFolderUpdateInputWithId := _FolderUpdateInputWithId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFolderUpdateInputWithId)

	if err != nil {
		return err
	}

	*o = FolderUpdateInputWithId(varFolderUpdateInputWithId)

	return err
}

type NullableFolderUpdateInputWithId struct {
	value *FolderUpdateInputWithId
	isSet bool
}

func (v NullableFolderUpdateInputWithId) Get() *FolderUpdateInputWithId {
	return v.value
}

func (v *NullableFolderUpdateInputWithId) Set(val *FolderUpdateInputWithId) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderUpdateInputWithId) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderUpdateInputWithId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderUpdateInputWithId(val *FolderUpdateInputWithId) *NullableFolderUpdateInputWithId {
	return &NullableFolderUpdateInputWithId{value: val, isSet: true}
}

func (v NullableFolderUpdateInputWithId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderUpdateInputWithId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


