/*
Files

Upload and manage files.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FileActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileActionResponse{}

// FileActionResponse struct for FileActionResponse
type FileActionResponse struct {
	Result *File `json:"result,omitempty"`
	// Time of completion of task.
	CompletedAt time.Time `json:"completedAt"`
	// Number of errors resulting from the task.
	NumErrors *int32 `json:"numErrors,omitempty"`
	// Timestamp of when the task was requested.
	RequestedAt *time.Time `json:"requestedAt,omitempty"`
	// Timestamp of when the task was started.
	StartedAt time.Time `json:"startedAt"`
	// Link to check the status of the requested task.
	Links *map[string]string `json:"links,omitempty"`
	// Descriptive error messages.
	Errors []StandardError `json:"errors,omitempty"`
	// ID of the requested task.
	TaskId string `json:"taskId"`
	// Current status of the task.
	Status string `json:"status"`
}

type _FileActionResponse FileActionResponse

// NewFileActionResponse instantiates a new FileActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileActionResponse(completedAt time.Time, startedAt time.Time, taskId string, status string) *FileActionResponse {
	this := FileActionResponse{}
	this.CompletedAt = completedAt
	this.StartedAt = startedAt
	this.TaskId = taskId
	this.Status = status
	return &this
}

// NewFileActionResponseWithDefaults instantiates a new FileActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileActionResponseWithDefaults() *FileActionResponse {
	this := FileActionResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FileActionResponse) GetResult() File {
	if o == nil || IsNil(o.Result) {
		var ret File
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetResultOk() (*File, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FileActionResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given File and assigns it to the Result field.
func (o *FileActionResponse) SetResult(v File) {
	o.Result = &v
}

// GetCompletedAt returns the CompletedAt field value
func (o *FileActionResponse) GetCompletedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompletedAt, true
}

// SetCompletedAt sets field value
func (o *FileActionResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt = v
}

// GetNumErrors returns the NumErrors field value if set, zero value otherwise.
func (o *FileActionResponse) GetNumErrors() int32 {
	if o == nil || IsNil(o.NumErrors) {
		var ret int32
		return ret
	}
	return *o.NumErrors
}

// GetNumErrorsOk returns a tuple with the NumErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetNumErrorsOk() (*int32, bool) {
	if o == nil || IsNil(o.NumErrors) {
		return nil, false
	}
	return o.NumErrors, true
}

// HasNumErrors returns a boolean if a field has been set.
func (o *FileActionResponse) HasNumErrors() bool {
	if o != nil && !IsNil(o.NumErrors) {
		return true
	}

	return false
}

// SetNumErrors gets a reference to the given int32 and assigns it to the NumErrors field.
func (o *FileActionResponse) SetNumErrors(v int32) {
	o.NumErrors = &v
}

// GetRequestedAt returns the RequestedAt field value if set, zero value otherwise.
func (o *FileActionResponse) GetRequestedAt() time.Time {
	if o == nil || IsNil(o.RequestedAt) {
		var ret time.Time
		return ret
	}
	return *o.RequestedAt
}

// GetRequestedAtOk returns a tuple with the RequestedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetRequestedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RequestedAt) {
		return nil, false
	}
	return o.RequestedAt, true
}

// HasRequestedAt returns a boolean if a field has been set.
func (o *FileActionResponse) HasRequestedAt() bool {
	if o != nil && !IsNil(o.RequestedAt) {
		return true
	}

	return false
}

// SetRequestedAt gets a reference to the given time.Time and assigns it to the RequestedAt field.
func (o *FileActionResponse) SetRequestedAt(v time.Time) {
	o.RequestedAt = &v
}

// GetStartedAt returns the StartedAt field value
func (o *FileActionResponse) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *FileActionResponse) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *FileActionResponse) GetLinks() map[string]string {
	if o == nil || IsNil(o.Links) {
		var ret map[string]string
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetLinksOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *FileActionResponse) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]string and assigns it to the Links field.
func (o *FileActionResponse) SetLinks(v map[string]string) {
	o.Links = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *FileActionResponse) GetErrors() []StandardError {
	if o == nil || IsNil(o.Errors) {
		var ret []StandardError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetErrorsOk() ([]StandardError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *FileActionResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []StandardError and assigns it to the Errors field.
func (o *FileActionResponse) SetErrors(v []StandardError) {
	o.Errors = v
}

// GetTaskId returns the TaskId field value
func (o *FileActionResponse) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *FileActionResponse) SetTaskId(v string) {
	o.TaskId = v
}

// GetStatus returns the Status field value
func (o *FileActionResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *FileActionResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *FileActionResponse) SetStatus(v string) {
	o.Status = v
}

func (o FileActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	toSerialize["completedAt"] = o.CompletedAt
	if !IsNil(o.NumErrors) {
		toSerialize["numErrors"] = o.NumErrors
	}
	if !IsNil(o.RequestedAt) {
		toSerialize["requestedAt"] = o.RequestedAt
	}
	toSerialize["startedAt"] = o.StartedAt
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	toSerialize["taskId"] = o.TaskId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *FileActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"completedAt",
		"startedAt",
		"taskId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileActionResponse := _FileActionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileActionResponse)

	if err != nil {
		return err
	}

	*o = FileActionResponse(varFileActionResponse)

	return err
}

type NullableFileActionResponse struct {
	value *FileActionResponse
	isSet bool
}

func (v NullableFileActionResponse) Get() *FileActionResponse {
	return v.value
}

func (v *NullableFileActionResponse) Set(val *FileActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFileActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFileActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileActionResponse(val *FileActionResponse) *NullableFileActionResponse {
	return &NullableFileActionResponse{value: val, isSet: true}
}

func (v NullableFileActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


