openapi: 3.0.1
info:
  description: ""
  title: Notes
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "If you had an offline conversation with a customer, you\
    \ could add a note to their contact record with the important takeaways from your\
    \ conversation."
  x-hubspot-related-documentation:
  - name: Notes Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/engagements/notes
  x-hubspot-introduction: Use the notes engagements API to include contextual information
    or associate an attachment with a CRM record. Other users in your HubSpot account
    will then be able to review the note and any attachments.
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Search
paths:
  /crm/v3/objects/notes/batch/read:
    post:
      operationId: post-/crm/v3/objects/notes/batch/read_read
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: "Read a batch of notes by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/notes/{noteId}:
    delete:
      description: "Move an Object identified by `{noteId}` to the recycling bin."
      operationId: "delete-/crm/v3/objects/notes/{noteId}_archive"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{noteId}`. `{noteId}` refers to\
        \ the internal object ID by default, or optionally any unique property value\
        \ as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: "get-/crm/v3/objects/notes/{noteId}_getById"
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{noteId}`.\
        \ `{noteId}` refers to the internal object ID by default, or optionally any\
        \ unique property value as specified by the `idProperty` query param. Provided\
        \ property values will be overwritten. Read-only and non-existent properties\
        \ will be ignored. Properties values can be cleared by passing an empty string."
      operationId: "patch-/crm/v3/objects/notes/{noteId}_update"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/notes/batch/archive:
    post:
      operationId: post-/crm/v3/objects/notes/batch/archive_archive
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Archive a batch of notes by ID
      tags:
      - Batch
  /crm/v3/objects/notes/batch/create:
    post:
      operationId: post-/crm/v3/objects/notes/batch/create_create
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create a batch of notes
      tags:
      - Batch
  /crm/v3/objects/notes/batch/update:
    post:
      operationId: post-/crm/v3/objects/notes/batch/update_update
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: "Update a batch of notes by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/notes:
    get:
      description: Read a page of notes. Control what is returned via the `properties`
        query param.
      operationId: get-/crm/v3/objects/notes_getPage
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: List
      tags:
      - Basic
    post:
      description: "Create a note with the given properties and return a copy of the\
        \ object, including the ID. Documentation and examples for creating standard\
        \ notes is provided."
      operationId: post-/crm/v3/objects/notes_create
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/notes/batch/upsert:
    post:
      description: Create or update records identified by a unique property value
        as specified by the `idProperty` query param. `idProperty` query param refers
        to a property whose values are unique for the object.
      operationId: post-/crm/v3/objects/notes/batch/upsert_upsert
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create or update a batch of notes by unique property values
      tags:
      - Batch
  /crm/v3/objects/notes/search:
    post:
      operationId: post-/crm/v3/objects/notes/search_doSearch
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.custom.read: View custom object records
            tickets: Read and write tickets
            crm.objects.goals.read: Read goals
            media_bridge.read: Read media and media events
            crm.objects.custom.write: Change custom object records
            e-commerce: e-commerce
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.services.read: Read services
            crm.objects.quotes.read: Quotes
            crm.objects.orders.write: Write orders
            crm.objects.carts.read: Read carts
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.leads.write: Modify lead objects
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.users.write: Write User CRM objects
            crm.objects.contacts.write: ' '
            crm.objects.companies.write: ' '
            crm.objects.listings.write: Write listings
            crm.objects.line_items.write: Line Items
            crm.objects.deals.write: ' '
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.invoices.read: Read invoices objects
            crm.objects.deals.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.line_items.read: Line Items
            crm.objects.services.write: Write services
            crm.objects.appointments.write: Write appointments
            crm.objects.leads.read: Read lead objects
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.appointments.read: Read appointments
            crm.objects.companies.read: ' '
            crm.objects.users.read: Read User CRM objects
            crm.objects.quotes.write: Quotes
            crm.objects.courses.write: Write courses
            crm.objects.carts.write: Write cart
            crm.objects.listings.read: Read listings
            crm.objects.contacts.read: ' '
            crm.objects.orders.read: Read Orders
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
